title: "Héctor Mondragón"
subtitle: "Political Science & Behavioral Data Analysis"
name: "Héctor Mondragón"
description: "Personal academic website, research papers, and data science projects."
url: "https://mondhector.github.io"

# Minimal Mistakes configuration
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" 

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Profile details
author:
  name: "Héctor Mondragón"
  #avatar: "/assets/images/bio-photo.jpg" # (Opcional) Puedes agregar tu foto en esta ruta después
  bio: "PhD Candidate in Political Science. Researching political psychology, ideology, social identity, and quantitative methods."
  location: "Mexico City"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MondHector"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hector.mondragon@gmail.com"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true